#version: '3.8'

services:

  database: #database service name
    image: postgres:15 #database image name and tag
    environment:
      POSTGRES_USER: username #database user
      POSTGRES_PASSWORD: 1234567890 #password for database
      POSTGRES_DB: test #database name
    ports:
      - "0000:0000" #ports for database operation (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data #the volume for saving data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s

  rabbitmq:    
    image: rabbitmq:4.1.7-management-alpine  
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 3s  
    container_name: rabbitmq    
    ports:      
      - "5672:5672"      
      - "15672:15672"    
    environment:      
      RABBITMQ_DEFAULT_USER: guest      
      RABBITMQ_DEFAULT_PASS: guest    
    volumes:      
      - rabbitmq_data:/var/lib/rabbitmq

  app: #app service name
    image: app:1.0 #application service name and tag
    build: .
    ports:
      - "8080:8080" #ports for application operation (host:container)
    environment:
      APP_VERSION: 2.4.2 #application version
      SERVER_ADDR: ${HOST_IP} #host ip
      DB_USER: postgres #database user
      DB_NAME: cookbook #database name
      DB_PASS: 1234567890 #password for database
      DB_HOST: database #database service name
      DB_PORT: 5432 #port for database operation (host:container)
      DB_SSLMODE: disable
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    

volumes:
  postgres_data:
  rabbitmq_data: